// globalStyles.js
import { styled, createGlobalStyle } from "styled-components";

export const GlobalStyle = createGlobalStyle`
  body {
    margin: 0px;
    padding: 0px;
    font-family: Arial, Helvetica, sans-serif;
  }
  
a{
  text-decoration: none;
  color: #fff;
}
.imgBackground{
      width: 100%;
    position: fixed;
    height: 100%;
    /* z-index: 1; */
    top: 0;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-9-29 9:54:47
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-top
 * ----------------------------------------
 */

`;

export const Container = styled.aside`
  display: flex;
`;

export const CodeView = styled.div`
  display: flex;
  color: #c5c5c5;
  flex-direction: column;
  border: 1px solid rgba(218, 224, 231, 0.168);
  border-radius: 10px;
  overflow: hidden;

  pre {
    margin: 0px !important;
  }
  code {
    border-top-right-radius: 0px !important;
    border-top-left-radius: 0px !important;
  }
  .viewCode {
    background-color: transparent;

    div {
      display: flex;
      flex-direction: row;
      padding: 10px 15px;
      border-bottom: 1px solid rgba(218, 224, 231, 0.168);
      width: 696px;
      margin-bottom: -1px;
      span:nth-of-type(1) {
        p {
          margin: 0px;
          color: #cecece;
          border: 1px solid rgba(218, 224, 231, 0.168);
          padding: 10px 20px;
          border-radius: 7px;
          &:hover {
            background-color: #0280fe34;
            color: #fff;
            cursor: pointer;
            border-color: #027ffe;
          }
        }
        .codeOpen {
          background-color: #0280fe34;
          color: #fff;
          cursor: pointer;
          border-color: #027ffe;
        }
      }
      span:nth-of-type(2) {
        display: flex;
        justify-content: end;
        align-items: end;
        flex: 1;
        gap: 10px;
        p {
          margin: 0px;
          color: #cecece;
          border: 1px solid rgba(218, 224, 231, 0.168);
          padding: 10px 20px;
          border-radius: 7px;
          &:hover {
            background-color: #15e84d20;
            color: #fff;
            cursor: pointer;
            border-color: #15e84c;
          }
        }

        .codeActive {
          background-color: #15e84d20;
          color: #fff;
          cursor: pointer;
          border-color: #15e84c;
        }
      }
    }
  }
  .boxCodeView {
    padding: 0px;
    margin-bottom: -15px;
    -webkit-animation: animationEffect 0.6s cubic-bezier(0.39, 0.575, 0.565, 1)
      both;
    animation: animationEffect 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  }
  @-webkit-keyframes animationEffect {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes animationEffect {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
`;
